from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import pymysql


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 522)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Download/4417104_database_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 601, 571))
        self.tabs.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);")
        self.tabs.setObjectName("tabs")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setStyleSheet("")
        self.tab_1.setObjectName("tab_1")
        self.label_title = QtWidgets.QLabel(self.tab_1)
        self.label_title.setGeometry(QtCore.QRect(100, 0, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.lineEdit_host = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_host.setGeometry(QtCore.QRect(0, 180, 111, 31))
        self.lineEdit_host.setStyleSheet("color: rgb(170, 170, 170);")
        self.lineEdit_host.setText("")
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.label_host = QtWidgets.QLabel(self.tab_1)
        self.label_host.setGeometry(QtCore.QRect(0, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_host.setFont(font)
        self.label_host.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_host.setObjectName("label_host")
        self.label_user = QtWidgets.QLabel(self.tab_1)
        self.label_user.setGeometry(QtCore.QRect(120, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_user.setObjectName("label_user")
        self.lineEdit_user = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_user.setGeometry(QtCore.QRect(110, 180, 121, 31))
        self.lineEdit_user.setStyleSheet("color: rgb(170, 170, 170);")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.label_password = QtWidgets.QLabel(self.tab_1)
        self.label_password.setGeometry(QtCore.QRect(240, 130, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_password.setGeometry(QtCore.QRect(230, 180, 141, 31))
        self.lineEdit_password.setStyleSheet("color: rgb(170, 170, 170);")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setPlaceholderText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_database = QtWidgets.QLabel(self.tab_1)
        self.label_database.setGeometry(QtCore.QRect(380, 130, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_database.setFont(font)
        self.label_database.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_database.setObjectName("label_database")
        self.lineEdit_database = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_database.setGeometry(QtCore.QRect(370, 180, 141, 31))
        self.lineEdit_database.setStyleSheet("color: rgb(170, 170, 170);")
        self.lineEdit_database.setText("")
        self.lineEdit_database.setObjectName("lineEdit_database")
        self.label_command = QtWidgets.QLabel(self.tab_1)
        self.label_command.setGeometry(QtCore.QRect(190, 300, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_command.setFont(font)
        self.label_command.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_command.setObjectName("label_command")
        self.lineEdit_command = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_command.setGeometry(QtCore.QRect(0, 360, 511, 51))
        self.lineEdit_command.setStyleSheet("color: rgb(170, 170, 170);")
        self.lineEdit_command.setText("")
        self.lineEdit_command.setPlaceholderText("")
        self.lineEdit_command.setObjectName("lineEdit_command")
        self.btn_execute = QtWidgets.QPushButton(self.tab_1)
        self.btn_execute.setGeometry(QtCore.QRect(190, 420, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_execute.setFont(font)
        self.btn_execute.setStyleSheet("background-color: rgb(222, 148, 0);\n"
"color: rgb(255, 255, 255);")
        self.btn_execute.setObjectName("btn_execute")
        self.sorry_text = QtWidgets.QLabel(self.tab_1)
        self.sorry_text.setGeometry(QtCore.QRect(120, 0, 400, 16))
        self.sorry_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.sorry_text.setObjectName("sorry_text")
        self.lineEdit_port = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_port.setGeometry(QtCore.QRect(200, 260, 111, 31))
        self.lineEdit_port.setStyleSheet("color: rgb(170, 170, 170);")
        self.lineEdit_port.setText("")
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.label_port = QtWidgets.QLabel(self.tab_1)
        self.label_port.setGeometry(QtCore.QRect(200, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_port.setFont(font)
        self.label_port.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_port.setObjectName("label_port")
        self.tabs.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_version = QtWidgets.QLabel(self.tab_2)
        self.label_version.setGeometry(QtCore.QRect(10, -10, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_version.setObjectName("label_version")
        self.label_updates = QtWidgets.QLabel(self.tab_2)
        self.label_updates.setGeometry(QtCore.QRect(10, 100, 361, 31))
        self.label_updates.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_updates.setObjectName("label_updates")
        self.label_version_2 = QtWidgets.QLabel(self.tab_2)
        self.label_version_2.setGeometry(QtCore.QRect(10, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_version_2.setFont(font)
        self.label_version_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_version_2.setObjectName("label_version_2")
        self.label_updates_2 = QtWidgets.QLabel(self.tab_2)
        self.label_updates_2.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_updates_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_updates_2.setObjectName("label_updates_2")
        self.label_updates_3 = QtWidgets.QLabel(self.tab_2)
        self.label_updates_3.setGeometry(QtCore.QRect(10, 160, 111, 31))
        self.label_updates_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_updates_3.setObjectName("label_updates_3")
        self.tabs.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.done()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Database Master"))
        self.label_title.setText(_translate("MainWindow", "DATABASE MASTER"))
        self.lineEdit_host.setPlaceholderText(_translate("MainWindow", "localhost"))
        self.label_host.setText(_translate("MainWindow", "Host"))
        self.label_user.setText(_translate("MainWindow", "User"))
        self.lineEdit_user.setPlaceholderText(_translate("MainWindow", "root"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.label_database.setText(_translate("MainWindow", "Database"))
        self.lineEdit_database.setPlaceholderText(_translate("MainWindow", "testdb"))
        self.label_command.setText(_translate("MainWindow", "Command"))
        self.btn_execute.setText(_translate("MainWindow", "Execute"))
        self.sorry_text.setText(_translate("MainWindow", "I sincerely apologize for this design. It will be improved in the future."))
        self.lineEdit_port.setPlaceholderText(_translate("MainWindow", "3306"))
        self.label_port.setText(_translate("MainWindow", "Port"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_1), _translate("MainWindow", "Menu"))
        self.label_version.setText(_translate("MainWindow", "Version: 1.0.1"))
        self.label_updates.setText(_translate("MainWindow", "1. The interface has been slightly updated (I made it clearer)."))
        self.label_version_2.setText(_translate("MainWindow", "What\'s new:"))
        self.label_updates_2.setText(_translate("MainWindow", "2. Added pop-ups."))
        self.label_updates_3.setText(_translate("MainWindow", "That\'s all :)"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("MainWindow", "Updates"))
    
    def done(self):
        self.btn_execute.clicked.connect(self.main)

    def main(self):
        successfullyMsg = QMessageBox()
        successfullyMsg.setWindowTitle("Done")
        successfullyMsg.setText("Operation completed successfully!")
        successfullyMsg.setInformativeText("Check your database.")
        successfullyMsg.setDetailedText("This popup was made at 11:48 pm. I don't know why you need this information. This text will be removed in version 1.1.0.")
        successfullyMsg.setStandardButtons(QMessageBox.Ok)
        successfullyMsg.buttonClicked.connect(self.ok_btn_action)

        errorMsg = QMessageBox()
        errorMsg.setWindowTitle("Error")
        errorMsg.setText("Something went wrong...")
        errorMsg.setStandardButtons(QMessageBox.Ok)
        errorMsg.buttonClicked.connect(self.ok_btn_action)

        try:
            connection = pymysql.connect(
                host=self.lineEdit_host.text(),
                port=int(self.lineEdit_port.text()),
                user=self.lineEdit_user.text(),
                password=self.lineEdit_password.text(),
                database=self.lineEdit_database.text(),
                cursorclass=pymysql.cursors.DictCursor
            )
            print("Successfully connected!")

            try:
                with connection.cursor() as cursor:
                    command = f"{self.lineEdit_command.text()}"
                    cursor.execute(command)
                    connection.commit()
                    print("Operation completed successfully!")
                    successfullyMsg.exec_()
            finally:
                connection.close()
        except Exception as ex:
            errorMsg.setInformativeText(f"{ex}")
            errorMsg.exec_()

            print("Something went wrong...")
            print(f"Cause: {ex}")

    def ok_btn_action(self, btn):
        if btn.text() == "OK":
            self.lineEdit_command.setText("")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
